name: Auto Update NSE Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install requests beautifulsoup4
    - name: Generate JS updater
      run: python get_nse_data.py
    - name: Commit & Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add nse_data_updater.js
        git commit -m "Auto-update data" || echo "No changes"
        git push
